enable:
  issues: true
  prs: true

comments:
  prs: |
    라벨러는 제목과 설명에서 특수 텍스트와 일치하는 모든 라벨을 적용했습니다.
    라벨을 검토하고 필요한 사항을 변경해 주시기 바랍니다.

labels:
  "Fix":
    include:
      - "\bFix\b"
  "Article":
    include:
      - "\bArticle\b"
  "Feature":
    include:
      - "\bFeature\b"
  "Techdept":
    include:
      - "\bTechdept\b"
